spring:
  application:
    name: inventory-service

  config:
    # Nạp file .env để Spring Boot có thể hiểu các biến ${VARIABLE}
    import: "optional:file:.env[.properties]"

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3307/inventory_db}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8&createDatabaseIfNotExist=true
#    username: ${DB_USER:postgres}
#    password: ${DB_PASSWORD:123456}
    username : root
    password : K59Ptl*100504
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      pool-name: HikariPool-Inventory
      maximum-pool-size: ${DB_INVENTORY_POOL_MAX:10}
      minimum-idle: ${DB_INVENTORY_POOL_MIN:5}
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 20000

  liquibase:
    enabled: ${LIQUIBASE_INVENTORY_ENABLED:true}
    change-log: classpath:liquibase/master.xml

  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_INVENTORY_DDL:none}
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: ${SHOW_INVENTORY_SQL:true}
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20

  sql:
    init:
      continue-on-error: false

server:
  port: ${SERVER_INVENTORY_PORT:8082}

logging:
  level:
    liquibase: ${LOG_LEVEL_LIQUIBASE_INVENTORY:INFO}
    org.liquibase: ${LOG_LEVEL_LIQUIBASE_INVENTORY:INFO}

eureka:
  client:
    service-url:
#      defaultZone: ${EUREKA_SERVER_URL:http://eureka-server:8761/eureka/}
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}
    instance:
      prefer-ip-address: true
