server:
  port: ${SERVER_BOOKING_TOUR_PORT:8089}

spring:
  application:
    name: booking-tour-service

  temporal:
    connection:
      target: ${TEMPORAL_URL:127.0.0.1:7233}
    workers:
      - task-queue: "BOOKING_TASK_QUEUE"
        workflow-classes:
          - com.vn.tech.booking_tour_service.workflow.BookingTaskWorkflowImpl
        activity-beans:
          - bookingTaskActivitiesImpl

logging:
  level:
    com:
      openhtmltopdf: ERROR

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://eureka-server:8761/eureka/}
  instance:
    prefer-ip-address: true

