server:
  port: ${SERVER_BOOKING_TOUR_PORT:8089}

spring:
  application:
    name: booking-tour-service

  temporal:
    connection:
      target: localhost:7233
    workers:
      - task-queue: "BOOKING_TASK_QUEUE"
        workflow-classes:
          - com.example.BookingTaskWorkflowImpl
        activity-beans:
          - bookTaskActivitiesImpl

logging:
  level:
    com:
      openhtmltopdf: ERROR

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
