server:
  port: ${SERVER_DOCUMENT_PORT:8083}

spring:
  application:
    name: document-service

logging:
  level:
    com:
      openhtmltopdf: ERROR

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://eureka-server:8761/eureka/}
  instance:
    prefer-ip-address: true
