server:
  port: ${SERVER_NOTIFICATION_PORT:8081}

spring:
  application:
    name: notification-service

  config:
    import: "optional:file:.env[.properties]"

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
#    username: ${MAIL_USERNAME}
    username: phamthanhlong725@gmail.com
#    password: ${MAIL_PASSWORD}
    password: vksc pggq japw nzkz
#    from: ${MAIL_FROM}
    from : phamthanhlong725@gmail.com
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
            required: true

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

eureka:
  client:
    service-url:
#      defaultZone: ${EUREKA_SERVER_URL:http://eureka-server:8761/eureka/}
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
